### ISSUE TITLE
How can I list folders and files ?

### ISSUE THREAD

**Issue by orgicus** [petervojtek/cordova-plugin-shell-exec#7]
I've just started using the plugin and tried something basic:

```javascript
window.ShellExec.exec('ls /storage', function(res){
          console.log('exit status: ' + res.exitStatus)
          console.log('cmd output: ' + res.output)
        })
```

but I get an IO error:
```java
 java.io.IOException: Error running exec(). Command: [ls /storage] Working Directory: null Environment: null
```

I've added these permissions in platforms/android/AndroidManifest.xml:
```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```
but I'm not sure what else I need to setup run the above command.
(The device I'm currently using is not rooted)

Any tips on how I should get past this error ?

Thank you,
George

**Comment by petervojtek** [comment]
hi @orgicus , first check if you can you run successfully the `ls` command on some directory from this list:
https://github.com/apache/cordova-plugin-file#android-file-system-layout, e.g. the `applicationStorageDirectory` mentioned there.

**Comment by jonongjs** [comment]
I think this may be due to my commit #6 
It changed the behaviour of ShellExec.exec() such that a single string argument is treated as a full command name itself. Perhaps a better choice would have been to detect if the argument was either a string or an array, and use the appropriate overload of Runtime.exec().

Otherwise, the solution on the end-user's side would be to always pass an array of strings to ShellExec.exec(), as in
```
window.ShellExec.exec(['ls', '/storage'], function(res){
          console.log('exit status: ' + res.exitStatus)
          console.log('cmd output: ' + res.output)
        });
```

**Comment by orgicus** [comment]
Sweet!
